# Generated by Django 4.2.3 on 2023-08-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentrecoad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='Email',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
