# Generated by Django 4.2.3 on 2023-08-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentrecoad', '0002_rename_email_student_email_alter_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
