# Generated by Django 4.2.3 on 2023-08-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentrecoad', '0004_alter_student_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='studenlist',
        ),
    ]
