# Generated by Django 4.2.3 on 2023-08-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentrecoad', '0005_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='studentrecoad.student'),
            preserve_default=False,
        ),
    ]
